# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: friends_test
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost

production:
  primary: &primary
    adapter: postgresql

    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %> 
    timeout: 5000

  queue:
    <<: *primary

  cache:
    <<: *primary
  
  cable:
    <<: *primary